### ISSUE TITLE
:loved doesn't seem to do anything love related

### ISSUE THREAD

**Issue by carnager** [thesquelched/suggestive#10]
I typed :loved in suggestive window and while it indeed swapped some albums around, it's definately not sorted by any means in regards to my loved tracks. The first few albums do have some loved tracks, but then there are a few albums which have no loved tracks at all near the top.

Or maybe I am misunderstanding what this option should do

**Comment by thesquelched** [comment]
So suggestive allows you to compose, for want of a better term, "orderers" on your library, of which `loved` is one.  By default, the orders are `loved` and `playcount` (you can change the defaults in your config with the `default_order` option in the `library` section; see (the sample config)[https://github.com/thesquelched/suggestive/blob/master/config/suggestive.conf.example]).

Assuming you didn't change the default, the `:loved` command would just apply that orderer on top of the existing ones, effectively giving additional weight to tracks that you marked loved.  You can reset the orderers with `esc`, or you can remove all ordering with the `:unordered` command.

**Comment by thesquelched** [comment]
And by "reset", I mean reset back to the default.  I'll try to write up some docs in the README for you.

**Comment by thesquelched** [comment]
README updated.
